stages:
    - build
    - test

variables:
    DOCKER_TLS_CERTDIR: ""


default:
    image: docker:latest
    services:
        - docker:dind
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    tags:
        - build


docker-build-release:
    stage: build
    script:
        - docker build --pull -t "$CI_REGISTRY_IMAGE:release" -t "$CI_COMMIT_TAG" .
        - docker push "$CI_REGISTRY_IMAGE" --all-tags
    only:
        - tags


docker-build-stable:
    stage: build
    script:
        - docker build --pull -t "$CI_REGISTRY_IMAGE:rc" -t "$CI_REGISTRY_IMAGE:stable" .
        - docker push "$CI_REGISTRY_IMAGE" --all-tags
    only:
        - master


docker-build-dev:
    stage: build
    script:
        - docker build --pull -t "$CI_REGISTRY_IMAGE:dev" -t "$CI_REGISTRY_IMAGE:latest" .
        - docker push "$CI_REGISTRY_IMAGE" --all-tags
    only:
        - develop


docker-build-other:
    stage: build
    script:
        - docker build --pull -t "$CI_REGISTRY_IMAGE:dev" -t "$CI_REGISTRY_IMAGE:latest" .
        - docker push "$CI_REGISTRY_IMAGE" --all-tags
    when: manual
